### ISSUE TITLE
need help,Thank you very much

### ISSUE THREAD

**Issue by oknixus** [exvim/ex-autocomplpop#1]
![1](https://cloud.githubusercontent.com/assets/4592706/6610865/4a783d2e-c8a0-11e4-848b-ce91312343fd.png)
![2](https://cloud.githubusercontent.com/assets/4592706/6610866/4a7e629e-c8a0-11e4-9744-a3eab29d8842.png)

First, when I enter 2 chars, the first line will be selected status,I could knock Enter key for input; But when I enter the third char, the selected status was missing, and I have to knock Ctrl-N to select the right one;
My problem is How to make the right one was selected when I enter the third char,the fourth char...the nth char. 
My englist is not good; Sorry!
I need your help! Thank your very much!

**Comment by jwu** [comment]
So far as I known, this is a bug of completion in Vim in Windows. Have you try the latest build of Vim? about Vim 7.4 (patch 216+), some people said it fixed by that.

**Comment by oknixus** [comment]
Thank you very much. Do you mean that I need to recompile the vim sources code ?

**Comment by jwu** [comment]
Yes, just download the latest source, and build it. I think somewhere should have nightly build version. Also, building from the source is not that difficult for gvim, even in Window, they got really friendly building script and README file. :D.

**Comment by oknixus** [comment]
@jwu Ok,Thanks:)
